name: 'Release'

on:
  workflow_call:
    inputs:
      gh-app-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true
    outputs:
      release-created:
        description: "Has the release been created"
        value: ${{ jobs.release.outputs.release-created }}
      major-tag:
        description: "Major version tag"
        value: ${{ jobs.release.outputs.major-tag }}
      minor-tag:
        description: "Minor version tag"
        value: ${{ jobs.release.outputs.minor-tag }}
      patch-tag:
        description: "Patch version tag"
        value: ${{ jobs.release.outputs.patch-tag }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-24.04
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      major-tag: ${{ steps.release.outputs.major }}
      minor-tag: ${{ steps.release.outputs.minor }}
      patch-tag: ${{ steps.release.outputs.patch }}
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ inputs.gh-app-id }}
          private-key: ${{ secrets.gh-app-private-key }}

      - name: Pre release new version
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: '.github/release-please-config.json'
          manifest-file: '.github/release-please-manifest.json'
